language: python
python:
- 3.6

services:
- docker

install:
- docker build -t max-sports-video-classifier .
- docker run -it -d -p 5000:5000 max-sports-video-classifier

before_script:
- pip install pytest requests
- sleep 10

script:
- pytest tests/test.py
